### ISSUE TITLE
请问一下适用的深澜版本

### ISSUE THREAD

**Issue by 2822132073** [Mmx233/BitSrunLoginGo#10]
麻烦问一下作者,适用的深澜版本

**Comment by Mmx233** [comment]
这个登录程序的登录逻辑并不是针对某个版本写的，绝大部分学校都能用这一套逻辑登录。而且深澜的版本挺杂的。我自己测试的时候用的是 v1.18 2016

**Comment by Mmx233** [comment]
如果还有更多问题，欢迎开启新 issue
