### ISSUE TITLE
允许在不开启 debug 模式的情况下写入日志到文件

### ISSUE THREAD

**Issue by 1715173329** [Mmx233/BitSrunLoginGo#11]
如题，同时希望可以自定义日志文件名称。

**Comment by Mmx233** [comment]
建议重新生成配置文件

[autoLogin_linux_386.zip](https://github.com/Mmx233/BitSrunLoginGo/files/9467410/autoLogin_linux_386.zip)
[autoLogin_linux_amd64.zip](https://github.com/Mmx233/BitSrunLoginGo/files/9467412/autoLogin_linux_amd64.zip)
[autoLogin_linux_arm.zip](https://github.com/Mmx233/BitSrunLoginGo/files/9467413/autoLogin_linux_arm.zip)
[autoLogin_linux_arm64.zip](https://github.com/Mmx233/BitSrunLoginGo/files/9467414/autoLogin_linux_arm64.zip)
[autoLogin_linux_mipsle.zip](https://github.com/Mmx233/BitSrunLoginGo/files/9467415/autoLogin_linux_mipsle.zip)
[autoLogin_windows_386.zip](https://github.com/Mmx233/BitSrunLoginGo/files/9467416/autoLogin_windows_386.zip)
[autoLogin_windows_amd64.zip](https://github.com/Mmx233/BitSrunLoginGo/files/9467417/autoLogin_windows_amd64.zip)
[autoLogin_darwin_amd64.zip](https://github.com/Mmx233/BitSrunLoginGo/files/9467408/autoLogin_darwin_amd64.zip)

**Comment by 1715173329** [comment]
好的，非常感谢！
