### ISSUE TITLE
请问多网口登录怎么设置

### ISSUE THREAD

**Issue by fuxiyc** [Mmx233/BitSrunLoginGo#12]
如果 eth0 eth1都要登录
interfaces: “”  要怎么设置呢？

**Comment by Mmx233** [comment]
`'eth[0-1]'` 自己多查查嘛

[正则表达式](https://www.google.com/search?q=%E6%AD%A3%E5%88%99%E8%A1%A8%E8%BE%BE%E5%BC%8F&oq=%E6%AD%A3%E5%88%99%E8%A1%A8%E8%BE%BE%E5%BC%8F)

[yaml 转义](https://www.google.com/search?q=yaml+%E8%BD%AC%E4%B9%89)
