### ISSUE TITLE
多个网口使用同一个IP请求

### ISSUE THREAD

**Issue by fuxiyc** [Mmx233/BitSrunLoginGo#15]
root@OpenWrt:~# /usr/local/srunlogin/autoLogin --config=/usr/local/srunlogin/Config.yaml
time="2022-09-21T15:54:01+08:00" level=info msg="[Guardian mode]"
time="2022-09-21T15:54:01+08:00" level=debug msg="网卡 lo 不匹配"
time="2022-09-21T15:54:01+08:00" level=debug msg="网卡 sit0 不匹配"
time="2022-09-21T15:54:01+08:00" level=debug msg="网卡 dummy0 不匹配"
time="2022-09-21T15:54:01+08:00" level=debug msg="网卡 eth0 不匹配"
time="2022-09-21T15:54:01+08:00" level=debug msg="网卡 eth1 不匹配"
time="2022-09-21T15:54:01+08:00" level=debug msg="网卡 eth2 不匹配"
time="2022-09-21T15:54:01+08:00" level=debug msg="网卡 eth3 不匹配"
time="2022-09-21T15:54:01+08:00" level=debug msg="网卡 utun 不匹配"
time="2022-09-21T15:54:01+08:00" level=debug msg="网卡 br-lan 不匹配"
time="2022-09-21T15:54:01+08:00" level=debug msg="有效匹配网卡：` **[{macvlan1 10.33.7.36:0} {macvlan2 10.33.7.37:0} {macvlan3 10.33.7.38:0}]"**`
time="2022-09-21T15:54:01+08:00" level=info msg=macvlan1
time="2022-09-21T15:54:01+08:00" level=info msg="Step.0: 正在检查状态"
time="2022-09-21T15:54:01+08:00" level=debug msg="HTTP GET  http://10.32.2.6/cgi-bin/rad_user_info"
time="2022-09-21T15:54:01+08:00" level=debug msg="jQuery1663746841049532976({\"client_ip\":\"10.33.7.38\",\"ecode\":0,\"error\":\"not_online_error\",\"error_msg\":\"\",\"online_ip\":\"10.33.7.38\",\"res\":\"not_online_error\",\"srun_ver\":\"SRunCGIAuthIntfSvr V1.18 B20211028\",\"st\":1663747068})"
time="2022-09-21T15:54:01+08:00" level=info msg="Step.1: 正在获取客户端ip"
time="2022-09-21T15:54:01+08:00" level=debug msg="ip:  10.33.7.38"
time="2022-09-21T15:54:01+08:00" level=info msg="Step.2: 正在获取token"
time="2022-09-21T15:54:01+08:00" level=debug msg="HTTP GET  http://10.32.2.6/cgi-bin/get_challenge"
time="2022-09-21T15:54:01+08:00" level=debug msg="jQuery1663746841057449837({\"challenge\":\"0908c40eb1f945356359121a3819a0340a37736c5c934b960916e5a4238e544d\",\"client_ip\":\"10.33.7.38\",\"ecode\":0,\"error\":\"ok\",\"error_msg\":\"\",\"expire\":\"60\",\"online_ip\":\"10.33.7.38\",\"res\":\"ok\",\"srun_ver\":\"SRunCGIAuthIntfSvr V1.18 B20211028\",\"st\":1663747068})"
time="2022-09-21T15:54:01+08:00" level=debug msg="token:  0908c40eb1f945356359121a3819a0340a37736c5c934b960916e5a4238e544d"
time="2022-09-21T15:54:01+08:00" level=info msg="Step.3: 执行登录…"
time="2022-09-21T15:54:01+08:00" level=debug msg="HTTP GET  http://10.32.2.6/cgi-bin/srun_portal"
time="2022-09-21T15:54:01+08:00" level=debug msg="jQuery1663746841062214576({\"ServerFlag\":0,\"ServicesIntfServerIP\":\"0.0.0.0\",\"ServicesIntfServerPort\":\"8001\",\"access_token\":\"0908c40eb1f945356359121a3819a0340a37736c5c934b960916e5a4238e544d\",\"checkout_date\":0,\"client_ip\":\"10.33.7.38\",\"ecode\":0,\"error\":\"ok\",\"error_msg\":\"\",\"online_ip\":\"10.33.7.38\",\"ploy_msg\":\"E0000: Login is successful.\",\"real_name\":\"\",\"remain_flux\":0,\"remain_times\":0,\"res\":\"ok\",\"srun_ver\":\"SRunCGIAuthIntfSvr V1.18 B20211028\",\"suc_msg\":\"login_ok\",\"sysver\":\"1.01.20211028\",\"username\":\"201936070036@unicom\",\"wallet_balance\":0})"
time="2022-09-21T15:54:01+08:00" level=info msg="登录结果: ok"
time="2022-09-21T15:54:01+08:00" level=info msg=macvlan2
time="2022-09-21T15:54:01+08:00" level=info msg="Step.0: 正在检查状态"
time="2022-09-21T15:54:01+08:00" level=debug msg="HTTP GET  http://10.32.2.6/cgi-bin/rad_user_info"
time="2022-09-21T15:54:01+08:00" level=debug msg="jQuery1663746841088999396({\"client_ip\":\"10.33.7.38\",\"ecode\":0,\"error\":\"not_online_error\",\"error_msg\":\"\",\"online_ip\":\"10.33.7.38\",\"res\":\"not_online_error\",\"srun_ver\":\"SRunCGIAuthIntfSvr V1.18 B20211028\",\"st\":1663747068})"
time="2022-09-21T15:54:01+08:00" level=info msg="Step.1: 正在获取客户端ip"
time="2022-09-21T15:54:01+08:00" level=debug msg="ip:  10.33.7.38"
time="2022-09-21T15:54:01+08:00" level=info msg="Step.2: 正在获取token"
time="2022-09-21T15:54:01+08:00" level=debug msg="HTTP GET  http://10.32.2.6/cgi-bin/get_challenge"
time="2022-09-21T15:54:01+08:00" level=debug msg="jQuery1663746841095553629({\"challenge\":\"0908c40eb1f945356359121a3819a0340a37736c5c934b960916e5a4238e544d\",\"client_ip\":\"10.33.7.38\",\"ecode\":0,\"error\":\"ok\",\"error_msg\":\"\",\"expire\":\"60\",\"online_ip\":\"10.33.7.38\",\"res\":\"ok\",\"srun_ver\":\"SRunCGIAuthIntfSvr V1.18 B20211028\",\"st\":1663747068})"
time="2022-09-21T15:54:01+08:00" level=debug msg="token:  0908c40eb1f945356359121a3819a0340a37736c5c934b960916e5a4238e544d"
time="2022-09-21T15:54:01+08:00" level=info msg="Step.3: 执行登录…"
time="2022-09-21T15:54:01+08:00" level=debug msg="HTTP GET  http://10.32.2.6/cgi-bin/srun_portal"
time="2022-09-21T15:54:01+08:00" level=debug msg="jQuery1663746841099915247({\"client_ip\":\"10.33.7.38\",\"ecode\":\"\",\"error\":\"login_error\",\"error_msg\":\"no_response_data_error\",\"online_ip\":\"10.33.7.38\",\"res\":\"login_error\",\"srun_ver\":\"SRunCGIAuthIntfSvr V1.18 B20211028\",\"st\":1663747068})"
time="2022-09-21T15:54:01+08:00" level=info msg="登录结果: login_error"
time="2022-09-21T15:54:01+08:00" level=error msg="网口  macvlan2 登录失败:  login_error"
time="2022-09-21T15:54:01+08:00" level=info msg=macvlan3
time="2022-09-21T15:54:01+08:00" level=info msg="Step.0: 正在检查状态"
time="2022-09-21T15:54:01+08:00" level=debug msg="HTTP GET  http://10.32.2.6/cgi-bin/rad_user_info"
time="2022-09-21T15:54:01+08:00" level=debug msg="jQuery1663746841116711376({\"client_ip\":\"10.33.7.38\",\"ecode\":0,\"error\":\"not_online_error\",\"error_msg\":\"\",\"online_ip\":\"10.33.7.38\",\"res\":\"not_online_error\",\"srun_ver\":\"SRunCGIAuthIntfSvr V1.18 B20211028\",\"st\":1663747068})"
time="2022-09-21T15:54:01+08:00" level=info msg="Step.1: 正在获取客户端ip"
time="2022-09-21T15:54:01+08:00" level=debug msg="ip:  10.33.7.38"
time="2022-09-21T15:54:01+08:00" level=info msg="Step.2: 正在获取token"
time="2022-09-21T15:54:01+08:00" level=debug msg="HTTP GET  http://10.32.2.6/cgi-bin/get_challenge"
time="2022-09-21T15:54:01+08:00" level=debug msg="jQuery1663746841123326422({\"challenge\":\"0908c40eb1f945356359121a3819a0340a37736c5c934b960916e5a4238e544d\",\"client_ip\":\"10.33.7.38\",\"ecode\":0,\"error\":\"ok\",\"error_msg\":\"\",\"expire\":\"60\",\"online_ip\":\"10.33.7.38\",\"res\":\"ok\",\"srun_ver\":\"SRunCGIAuthIntfSvr V1.18 B20211028\",\"st\":1663747068})"
time="2022-09-21T15:54:01+08:00" level=debug msg="token:  0908c40eb1f945356359121a3819a0340a37736c5c934b960916e5a4238e544d"
time="2022-09-21T15:54:01+08:00" level=info msg="Step.3: 执行登录…"
time="2022-09-21T15:54:01+08:00" level=debug msg="HTTP GET  http://10.32.2.6/cgi-bin/srun_portal"
time="2022-09-21T15:54:01+08:00" level=debug msg="jQuery1663746841127485178({\"client_ip\":\"10.33.7.38\",\"ecode\":\"\",\"error\":\"login_error\",\"error_msg\":\"no_response_data_error\",\"online_ip\":\"10.33.7.38\",\"res\":\"login_error\",\"srun_ver\":\"SRunCGIAuthIntfSvr V1.18 B20211028\",\"st\":1663747068})"
time="2022-09-21T15:54:01+08:00" level=info msg="登录结果: login_error"
time="2022-09-21T15:54:01+08:00" level=error msg="网口  macvlan3 登录失败:  login_error"

**Comment by Mmx233** [comment]
这个 ip 是深澜给你分配的 ip，也就是说你的 vlan 被识别为同一个设备，即使你用了两个 lan 口

**Comment by fuxiyc** [comment]
主要是我测试了多次，有时候用两个ip登录了两个，有时候就用一个ip登录一个

**Comment by fuxiyc** [comment]
我看`time="2022-09-21T16:54:18+08:00" level=debug msg="有效匹配网卡： [{macvlan1 10.33.7.31:0} {macvlan2 10.33.7.30:0} {macvlan3 10.33.7.29:0}]"`这里已经识别了ip
为什么`time="2022-09-21T16:54:18+08:00" level=debug msg="jQuery1663750458531249802({\"client_ip\":\"10.33.7.29\",\"ecode\":0,\"error\":\"not_online_error\",\"error_msg\":\"\",\"online_ip\":\"10.33.7.29\",\"res\":\"not_online_error\",\"srun_ver\":\"SRunCGIAuthIntfSvr V1.18 B20211028\",\"st\":1663750686})"`

`time="2022-09-21T16:54:18+08:00" level=debug msg="jQuery1663750458538994387({\"client_ip\":\"10.33.7.29\",\"ecode\":\"\",\"error\":\"login_error\",\"error_msg\":\"no_response_data_error\",\"online_ip\":\"10.33.7.29\",\"res\":\"login_error\",\"srun_ver\":\"SRunCGIAuthIntfSvr V1.18 B20211028\",\"st\":1663750686})"`
这里为什么这里是同一个ip

**Comment by Mmx233** [comment]
这个是深澜 api 给的 ip，不是拿你 DHCP 到的 ip 直接去认证的

**Comment by Mmx233** [comment]
也就是 step0 的 ip

**Comment by fuxiyc** [comment]
所以没办法进行多网卡登录了吗，是必须两个物理网口才能正常用插件登录吗

**Comment by Mmx233** [comment]
> 所以没办法进行多网卡登录了吗，是必须两个物理网口才能正常用插件登录吗

就算你手动登录也是不行的吧

**Comment by fuxiyc** [comment]
可以呀，我手动是可以登录成功的呀，只不过不知到为啥负载均衡没正常的用起来

**Comment by Mmx233** [comment]
> 可以呀，我手动是可以登录成功的呀，只不过不知到为啥负载均衡没正常的用起来

我也试过手动，有两种情况。一种是一边登了另一边就自己退了，速度不变。另一种是我用两个路由器登陆，再用一个负载均衡，流量两边对半分，负载均衡是有效的，但是总速度还是不变，应该是检测到了

**Comment by fuxiyc** [comment]
我手动登录了多个网口，负载均衡界面显示成功，但实际没生效，不清楚是不是我这里禁止了
