### ISSUE TITLE
双拨问题

### ISSUE THREAD

**Issue by zhangxxxl** [Mmx233/BitSrunLoginGo#18]
读取配置文件失败： While parsing config: yaml: line 7: mapping values are not allowed in this context
这一行我是默认没动过的，但是提示

**Comment by Mmx233** [comment]
可能上下文中混用了 tab 和空格，可以重新生成或者用 json

**Comment by zhangxxxl** [comment]
01:00.0 Ethernet controller: Intel Corporation I211 Gigabit Network Connection (rev 03)
02:00.0 Ethernet controller: Intel Corporation I211 Gigabit Network Connection (rev 03)
我的设备里两个网卡，我在网卡选项里应该怎么填写

**Comment by Mmx233** [comment]
> 01:00.0 Ethernet controller: Intel Corporation I211 Gigabit Network Connection (rev 03) 02:00.0 Ethernet controller: Intel Corporation I211 Gigabit Network Connection (rev 03) 我的设备里两个网卡，我在网卡选项里应该怎么填写

请参照 #15 #16 自行填写

**Comment by zhangxxxl** [comment]
我偶然发现https://github.com/tkkcc/mentohust这里的示例,不知道是否可以参考

**Comment by zhangxxxl** [comment]
我偶然发现了这里有示例，不知是否可以参考https://github.com/tkkcc/mentohust

**Comment by Mmx233** [comment]
差不多是这样配置的，但是我也试过手动，有两种情况。一种是一边登了另一边就自己退了，速度不变。另一种是我用两个路由器登陆，再用一个负载均衡，流量两边对半分，负载均衡是有效的，但是总速度大部分情况下还是不变，偶尔能叠加，应该是检测到了。
简单来说就是没啥用

**Comment by zhangxxxl** [comment]
这个博主实现了完美双拨深澜https://github.com/zu1k/sdusrun/releases
https://zu1k.com/posts/tutorials/campus-network-speed-overlay/

**Comment by Mmx233** [comment]
看上去不错诶，我可以修改登录程序以支持强制多 ip 认证，但是我手头没有能刷的路由器，可能需要你来尝试

zhangxxxl ***@***.***> 于 2022年10月13日周四 00:44写道：

**Comment by zhangxxxl** [comment]
他是通过严格的流量控制实现的，普通的双拨，服务器识别到流量来自同一网关就会限速，他的博客文章里有提到

**Comment by Mmx233** [comment]
但是事实上我自己试的时候用了两个账号，但是还是不成功，应该还有深度包检测

zhangxxxl ***@***.***> 于 2022年10月13日周四 21:43写道：

**Comment by zhangxxxl** [comment]
我用两个路由器实现了双拨叠加，网口-网关1-网关2，网口-网关2，我发现刚登陆的一两分钟内会被检测，当我等一会再把网关1与2连接时就不会被检测，然后是登陆一天以后会被掉线一个，

**Comment by zhangxxxl** [comment]
所以要想实现稳定的双拨，必须要严格的流量控制，像https://zu1k.com/posts/tutorials/campus-network-speed-overlay/他这样

**Comment by zhangxxxl** [comment]
我找到双拨会掉线的原因了，是你的脚本有问题，我用几个路由试，只要用你的脚本就会只能在线一个，别的都会掉线，而我一个用你的脚本，一个用手机认证，就不会掉线了

**Comment by Mmx233** [comment]
> 我找到双拨会掉线的原因了，是你的脚本有问题，我用几个路由试，只要用你的脚本就会只能在线一个，别的都会掉线，而我一个用你的脚本，一个用手机认证，就不会掉线了

我知道了，应该是取设备 ip 的逻辑有问题

**Comment by Mmx233** [comment]
我加了随机 UA，试试

[autoLogin_darwin_amd64.zip](https://github.com/Mmx233/BitSrunLoginGo/files/9895235/autoLogin_darwin_amd64.zip)
[autoLogin_linux_386.zip](https://github.com/Mmx233/BitSrunLoginGo/files/9895236/autoLogin_linux_386.zip)
[autoLogin_linux_amd64.zip](https://github.com/Mmx233/BitSrunLoginGo/files/9895237/autoLogin_linux_amd64.zip)
[autoLogin_linux_arm.zip](https://github.com/Mmx233/BitSrunLoginGo/files/9895239/autoLogin_linux_arm.zip)
[autoLogin_linux_arm64.zip](https://github.com/Mmx233/BitSrunLoginGo/files/9895240/autoLogin_linux_arm64.zip)
[autoLogin_linux_mipsle.zip](https://github.com/Mmx233/BitSrunLoginGo/files/9895241/autoLogin_linux_mipsle.zip)
[autoLogin_windows_386.zip](https://github.com/Mmx233/BitSrunLoginGo/files/9895242/autoLogin_windows_386.zip)
[autoLogin_windows_amd64.zip](https://github.com/Mmx233/BitSrunLoginGo/files/9895243/autoLogin_windows_amd64.zip)

**Comment by zhangxxxl** [comment]
我觉得和ua没关系，我试了一个路由器改ua，一个不改，还是会掉线

**Comment by Mmx233** [comment]
> 我觉得和ua没关系，我试了一个路由器改ua，一个不改，还是会掉线

之前的登录程序并不支持修改 UA，你是怎么改 UA 的

**Comment by zhangxxxl** [comment]
https://www.notion.so/sunbk201public/OpenWrt-f59ae1a76741486092c27bc24dbadc59
这是防检测部署的教程，

**Comment by Mmx233** [comment]
那直接支持取用网卡 DHCP 到的 ip 好了，再加个 flag 强行指定

**Comment by zhangxxxl** [comment]
现在是用的模拟浏览器获取IP的方式吗，要是这样的话就说的通了，应该是被识别成一个设备了，

**Comment by Mmx233** [comment]
> 现在是用的模拟浏览器获取IP的方式吗，要是这样的话就说的通了，应该是被识别成一个设备了，

是的，完全模拟

**Comment by zhangxxxl** [comment]
我猜深澜并不是靠识别ua来识别设备的，因为opwrt不配置防ua检测一样可以用

**Comment by Mmx233** [comment]
单网卡模式使用 flag  --ip 指定 ip，多网卡模式配置文件 settings.basic.use_dhcp_ip 设为 ture 取用网卡 ip

[autoLogin_darwin_amd64.zip](https://github.com/Mmx233/BitSrunLoginGo/files/9895273/autoLogin_darwin_amd64.zip)
[autoLogin_linux_386.zip](https://github.com/Mmx233/BitSrunLoginGo/files/9895274/autoLogin_linux_386.zip)
[autoLogin_linux_amd64.zip](https://github.com/Mmx233/BitSrunLoginGo/files/9895275/autoLogin_linux_amd64.zip)
[autoLogin_linux_arm.zip](https://github.com/Mmx233/BitSrunLoginGo/files/9895276/autoLogin_linux_arm.zip)
[autoLogin_linux_arm64.zip](https://github.com/Mmx233/BitSrunLoginGo/files/9895277/autoLogin_linux_arm64.zip)
[autoLogin_linux_mipsle.zip](https://github.com/Mmx233/BitSrunLoginGo/files/9895278/autoLogin_linux_mipsle.zip)
[autoLogin_windows_386.zip](https://github.com/Mmx233/BitSrunLoginGo/files/9895279/autoLogin_windows_386.zip)
[autoLogin_windows_amd64.zip](https://github.com/Mmx233/BitSrunLoginGo/files/9895280/autoLogin_windows_amd64.zip)

**Comment by Mmx233** [comment]
在线状态逻辑还是保留了原来的逻辑，可能影响多网卡模式正常运行。如果真的存在这个问题的话，我再加一个选择不用深澜 api 检查在线状态的功能

**Comment by zhangxxxl** [comment]
我试试

**Comment by zhangxxxl** [comment]
root@OpenWrt:~# ./autoLogin
FATA[0000] [init] 解析配置文件失败： 1 error(s) decoding:

* cannot parse 'settings.basic.use_dhcp_ip' as bool: strconv.ParseBool: parsing "ture": invalid syntax

**Comment by Mmx233** [comment]
true……

**Comment by zhangxxxl** [comment]
哈哈哈，我说呢，你打错了，我直接复制的，我还来回看了两次

**Comment by Mmx233** [comment]
> 哈哈哈，我说呢，你打错了，我直接复制的，我还来回看了两次

😂

**Comment by zhangxxxl** [comment]
> 单网卡模式使用 flag --ip 指定 ip，多网卡模式配置文件 settings.basic.use_dhcp_ip 设为 ture 取用网卡 ip
> 
> [autoLogin_darwin_amd64.zip](https://github.com/Mmx233/BitSrunLoginGo/files/9895273/autoLogin_darwin_amd64.zip) [autoLogin_linux_386.zip](https://github.com/Mmx233/BitSrunLoginGo/files/9895274/autoLogin_linux_386.zip) [autoLogin_linux_amd64.zip](https://github.com/Mmx233/BitSrunLoginGo/files/9895275/autoLogin_linux_amd64.zip) [autoLogin_linux_arm.zip](https://github.com/Mmx233/BitSrunLoginGo/files/9895276/autoLogin_linux_arm.zip) [autoLogin_linux_arm64.zip](https://github.com/Mmx233/BitSrunLoginGo/files/9895277/autoLogin_linux_arm64.zip) [autoLogin_linux_mipsle.zip](https://github.com/Mmx233/BitSrunLoginGo/files/9895278/autoLogin_linux_mipsle.zip) [autoLogin_windows_386.zip](https://github.com/Mmx233/BitSrunLoginGo/files/9895279/autoLogin_windows_386.zip) [autoLogin_windows_amd64.zip](https://github.com/Mmx233/BitSrunLoginGo/files/9895280/autoLogin_windows_amd64.zip)

不行，还是会掉，而且这回一个用手机认证一个用脚本 ，都只能有一个在线了

**Comment by Mmx233** [comment]
那大概就不是脚本的问题了

zhangxxxl ***@***.***> 于 2022年11月2日周三 12:22写道：

**Comment by Mmx233** [comment]
solved in #23
