### ISSUE TITLE
Pull Request 预请求

### ISSUE THREAD

**Issue by Revincx** [Mmx233/BitSrunLoginGo#19]
感谢大佬的项目，我们学校也是用的深澜，于是我 fork 了一下仓库对源码进行了修改。现在想提出 PR 把我的修改合并上来，但是因为我刚接触 Golang 很多地方可能写得不是很好，而且目前我自己的魔改有点多，所以想先讨论一下需要保留那些东西？可以的话还请多指教。

我的 Fork: https://github.com/Revincx/bitsrunlogin-go/commits/main

**Comment by Mmx233** [comment]
https://github.com/Revincx/bitsrunlogin-go/blob/36c37dd82fcdb6f7aae2450572f7ed718dfbbe94/controllers/guardian.go#L65

少了右半括号，而且我觉得半角符号和中文之间最好加个空格

**Comment by Revincx** [comment]
> https://github.com/Revincx/bitsrunlogin-go/blob/36c37dd82fcdb6f7aae2450572f7ed718dfbbe94/controllers/guardian.go#L65
> 
> 少了右半括号，而且我觉得半角符号和中文之间最好加个空格

ok谢谢提醒，不过在其他的代码逻辑上还有需要修改的吗，尤其是我新增的那个 SlientMode

**Comment by Mmx233** [comment]
https://github.com/Revincx/bitsrunlogin-go/blob/36c37dd82fcdb6f7aae2450572f7ed718dfbbe94/global/log.go#L42

这个地方为啥要禁用颜色输出啊

**Comment by Revincx** [comment]
> https://github.com/Revincx/bitsrunlogin-go/blob/36c37dd82fcdb6f7aae2450572f7ed718dfbbe94/global/log.go#L42
> 
> 这个地方为啥要禁用颜色输出啊

如果开启带颜色的输出的话就会导致输出的 log 文件里夹杂颜色控制码，非常的不美观

**Comment by Mmx233** [comment]
logrus 是可以把 level 设为 0 来禁用输出的，每一行日志都加一个判断不大优雅。还是说 slientMode 只去除登录步骤的日志

![image](https://user-images.githubusercontent.com/36563672/196074169-60dfcd90-78d6-4ffe-ad3c-fe8b743aa9bb.png)

**Comment by Mmx233** [comment]
> > https://github.com/Revincx/bitsrunlogin-go/blob/36c37dd82fcdb6f7aae2450572f7ed718dfbbe94/global/log.go#L42
> > 这个地方为啥要禁用颜色输出啊
> 
> 如果开启带颜色的输出的话就会导致输出的 log 文件里夹杂颜色控制码，非常的不美观

是吗，我自己测试的时候不会这呀，还是说这是用了 nested 之后才有

![image](https://user-images.githubusercontent.com/36563672/196074579-0591161b-27d0-4aae-b87a-cb340a714794.png)

**Comment by Revincx** [comment]
> logrus 是可以把 level 设为 0 来禁用输出的，每一行日志都加一个判断不大优雅。还是说 slientMode 只去除登录步骤的日志
> 
> ![image](https://user-images.githubusercontent.com/36563672/196074169-60dfcd90-78d6-4ffe-ad3c-fe8b743aa9bb.png)

我的目的是想去除检测在线状态的日志。原因是我们的校园网有时会掉线非常频繁，所以就需要检测频率尽可能的低，我目前填的是 5s。但开始日志输出时每检测一下都会写入四五行日志，一天下来日志文件就能膨胀到好几M。所以就加了个安静模式用来关闭正常在线时的日常输出，不过掉线登录的时候的日志还是要记录的。

**Comment by Mmx233** [comment]
> > logrus 是可以把 level 设为 0 来禁用输出的，每一行日志都加一个判断不大优雅。还是说 slientMode 只去除登录步骤的日志
> > ![image](https://user-images.githubusercontent.com/36563672/196074169-60dfcd90-78d6-4ffe-ad3c-fe8b743aa9bb.png)
> 
> 我的目的是想去除检测在线状态的日志。原因是我们的校园网有时会掉线非常频繁，所以就需要检测频率尽可能的低，我目前填的是 5s。但开始日志输出时每检测一下都会写入四五行日志，一天下来日志文件就能膨胀到好几M。所以就加了个安静模式用来关闭正常在线时的日常输出，不过掉线登录的时候的日志还是要记录的。

那这样的话我觉得可以把在线的日志调高一级，改成 debug 日志，完全可以不用加一个模式的

**Comment by Mmx233** [comment]
然后再加一个日志大小限制功能

**Comment by Revincx** [comment]
> > > https://github.com/Revincx/bitsrunlogin-go/blob/36c37dd82fcdb6f7aae2450572f7ed718dfbbe94/global/log.go#L42
> > > 这个地方为啥要禁用颜色输出啊
> > 
> > 
> > 如果开启带颜色的输出的话就会导致输出的 log 文件里夹杂颜色控制码，非常的不美观
> 
> 是吗，我自己测试的时候不会呀，还是说这是用了 nested 之后才有
> 
> ![image](https://user-images.githubusercontent.com/36563672/196074579-0591161b-27d0-4aae-b87a-cb340a714794.png)

这个的话是因为 logrus 在使用默认的 TextFormater 时会检测是否有 TTY，如果有的话输出的日志就会变成 dump 之后的格式，也就是这个截图的样子。我感觉这种格式不太美观才换了 nested。另外如果开启了 write_file 的话，即使在 TTY 运行不还是没用颜色输出嘛。

**Comment by Mmx233** [comment]
> > > > https://github.com/Revincx/bitsrunlogin-go/blob/36c37dd82fcdb6f7aae2450572f7ed718dfbbe94/global/log.go#L42
> > > > 这个地方为啥要禁用颜色输出啊
> > > 
> > > 
> > > 如果开启带颜色的输出的话就会导致输出的 log 文件里夹杂颜色控制码，非常的不美观
> > 
> > 
> > 是吗，我自己测试的时候不会呀，还是说这是用了 nested 之后才有
> > ![image](https://user-images.githubusercontent.com/36563672/196074579-0591161b-27d0-4aae-b87a-cb340a714794.png)
> 
> 这个的话是因为 logrus 在使用默认的 TextFormater 时会检测是否有 TTY，如果有的话输出的日志就会变成 dump 之后的格式，也就是这个截图的样子。我感觉这种格式不太美观才换了 nested。另外如果开启了 write_file 的话，即使在 TTY 运行不还是没颜色输出嘛。

那我们也判断一下，别一棒子砍掉（

**Comment by Revincx** [comment]
> > > > > https://github.com/Revincx/bitsrunlogin-go/blob/36c37dd82fcdb6f7aae2450572f7ed718dfbbe94/global/log.go#L42
> > > > > 这个地方为啥要禁用颜色输出啊
> > > > 
> > > > 
> > > > 如果开启带颜色的输出的话就会导致输出的 log 文件里夹杂颜色控制码，非常的不美观
> > > 
> > > 
> > > 是吗，我自己测试的时候不会呀，还是说这是用了 nested 之后才有
> > > ![image](https://user-images.githubusercontent.com/36563672/196074579-0591161b-27d0-4aae-b87a-cb340a714794.png)
> > 
> > 
> > 这个的话是因为 logrus 在使用默认的 TextFormater 时会检测是否有 TTY，如果有的话输出的日志就会变成 dump 之后的格式，也就是这个截图的样子。我感觉这种格式不太美观才换了 nested。另外如果开启了 write_file 的话，即使在 TTY 运行不还是没颜色输出嘛。
> 
> 那我们也判断一下，别一棒子砍掉（

也不是不行，不过我刚接触不太懂怎么判断（

**Comment by Mmx233** [comment]
我去赶一下其他 ddl，下午继续缕😘

**Comment by Revincx** [comment]
> 我去赶一下其他 ddl，下午继续缕kissing_heart

hello，可以看下 pr 嘛 🥺

**Comment by Mmx233** [comment]
> > 我去赶一下其他 ddl，下午继续缕kissing_heart
> 
> hello，可以看下 pr 嘛 🥺

超，忘了这回事，磕头了

**Comment by Mmx233** [comment]
![image](https://user-images.githubusercontent.com/36563672/197124218-b83c4d90-43f9-4bd8-9707-e8c26388eff6.png)

这个地方不能乱改喔，程序逻辑会变化非常大

**Comment by Revincx** [comment]
> 目前还有一个问题就是单次登录不开 debug 什么都看不到

要不在不开启守护模式的情况下仍然打印登录检测的日志？

**Comment by Mmx233** [comment]
> > 目前还有一个问题就是单次登录不开 debug 什么都看不到
> 
> 要不在不开启守护模式的情况下仍然打印登录检测的日志？

快改完了，我打算在不开启守护模式的情况下仍然打印状态检查之类的，其他的仍然 debug

**Comment by Revincx** [comment]
> > > 目前还有一个问题就是单次登录不开 debug 什么都看不到
> > 
> > 
> > 要不在不开启守护模式的情况下仍然打印登录检测的日志？
> 
> 快改完了，我打算在不开启守护模式的情况下仍然打印状态检查之类的，其他的仍然 debug

好的，这样应该比较可行

**Comment by Mmx233** [comment]
已经发布了 https://github.com/Mmx233/BitSrunLoginGo/releases/tag/v3.4
