### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by zhangxxxl** [Mmx233/BitSrunLoginGo#21]
运行出错，状态异常:  Get "http://http//218.104.96.75/srun_portal_pc?_=1658169365716317331&ac_id=8&callback=jQuery1658169365716317331&theme=pro&wlanuserip=100.83.190.241%2Fcgi-bin%2Frad_user_info": dial tcp: lookup http on 127.0.0.1:53: no such host

我的好几个路由器都会报这个错误，都是opwrt

**Comment by Mmx233** [comment]
请严格按照配置文件说明填写

`form.domain` 为域名，不能添加 `http://` 协议头
