### ISSUE TITLE
请问ac_id能否自动获取

### ISSUE THREAD

**Issue by qiaoborui** [Mmx233/BitSrunLoginGo#24]
如API地址为http://10.186.255.33,默认打开ac_id为1，但是可以访问1.1.1.1会自动重定向到含有正确ac_id的url

**Comment by Mmx233** [comment]
这种重定向可能不能在任何情况下都正常工作，而且会让登录流程多一个请求。既然这个参数和别的参数在同一个请求里，那顺便复制一下问题也不大。添加 ac_id 自动获取可能并不划算

**Comment by qiaoborui** [comment]
是这样的，可能只是我们学校是这样做的，但是手动复制一定程度上降低了自动化的程度，假如设备的位置一直在变，导致acid的值也在改变，就需要每次手动修改，那么能否增添一个命令行参数用来覆盖配置文件中的acid，使得可以使用在使用shell脚本等工具拿到acid后传入bitsrun程序。

发自我的 iPad

在 2023年6月3日，17:18，Mmx ***@***.***> 写道：

﻿

这种重定向可能不能在任何情况下都正常工作，而且会让登录流程多一个请求。既然这个参数和别的参数在同一个请求里，那顺便复制一下问题也不大。添加 ac_id 自动获取可能并不划算

**Comment by Mmx233** [comment]
好的，稍后几天我会添加该功能

**Comment by Mmx233** [comment]
我不建议现在就关闭 issue，我需要它提醒我还有个活没干。而且之后需要等你反馈良好之后我才会发布正式版，也就是说我们还要在这个 issue 交流

**Comment by qiaoborui** [comment]
你说的很对，谢谢提醒，我将会reopen this issue

**Comment by Mmx233** [comment]
现在可以用 `--acid 9` 覆盖配置文件 `acid` 配置，可以使用 `--auto-acid` 开启自动检测。测试时请使用 `--debug` 打开测试日志以便追踪错误。

[bitsrun_aix_ppc64.zip](https://github.com/Mmx233/BitSrunLoginGo/files/11645700/bitsrun_aix_ppc64.zip)
[bitsrun_android_arm64.zip](https://github.com/Mmx233/BitSrunLoginGo/files/11645701/bitsrun_android_arm64.zip)
[bitsrun_darwin_amd64.zip](https://github.com/Mmx233/BitSrunLoginGo/files/11645702/bitsrun_darwin_amd64.zip)
[bitsrun_darwin_arm64.zip](https://github.com/Mmx233/BitSrunLoginGo/files/11645703/bitsrun_darwin_arm64.zip)
[bitsrun_dragonfly_amd64.zip](https://github.com/Mmx233/BitSrunLoginGo/files/11645704/bitsrun_dragonfly_amd64.zip)
[bitsrun_freebsd_386.zip](https://github.com/Mmx233/BitSrunLoginGo/files/11645705/bitsrun_freebsd_386.zip)
[bitsrun_freebsd_amd64.zip](https://github.com/Mmx233/BitSrunLoginGo/files/11645706/bitsrun_freebsd_amd64.zip)
[bitsrun_freebsd_arm.zip](https://github.com/Mmx233/BitSrunLoginGo/files/11645707/bitsrun_freebsd_arm.zip)
[bitsrun_freebsd_arm64.zip](https://github.com/Mmx233/BitSrunLoginGo/files/11645708/bitsrun_freebsd_arm64.zip)
[bitsrun_illumos_amd64.zip](https://github.com/Mmx233/BitSrunLoginGo/files/11645709/bitsrun_illumos_amd64.zip)
[bitsrun_js_wasm.zip](https://github.com/Mmx233/BitSrunLoginGo/files/11645710/bitsrun_js_wasm.zip)
[bitsrun_linux_386.zip](https://github.com/Mmx233/BitSrunLoginGo/files/11645711/bitsrun_linux_386.zip)
[bitsrun_linux_amd64.zip](https://github.com/Mmx233/BitSrunLoginGo/files/11645712/bitsrun_linux_amd64.zip)
[bitsrun_linux_arm.zip](https://github.com/Mmx233/BitSrunLoginGo/files/11645713/bitsrun_linux_arm.zip)
[bitsrun_linux_arm64.zip](https://github.com/Mmx233/BitSrunLoginGo/files/11645714/bitsrun_linux_arm64.zip)
[bitsrun_linux_mips.zip](https://github.com/Mmx233/BitSrunLoginGo/files/11645715/bitsrun_linux_mips.zip)
[bitsrun_linux_mips_softfloat.zip](https://github.com/Mmx233/BitSrunLoginGo/files/11645716/bitsrun_linux_mips_softfloat.zip)
[bitsrun_linux_mips64.zip](https://github.com/Mmx233/BitSrunLoginGo/files/11645717/bitsrun_linux_mips64.zip)
[bitsrun_linux_mips64_softfloat.zip](https://github.com/Mmx233/BitSrunLoginGo/files/11645718/bitsrun_linux_mips64_softfloat.zip)
[bitsrun_linux_mips64le.zip](https://github.com/Mmx233/BitSrunLoginGo/files/11645719/bitsrun_linux_mips64le.zip)
[bitsrun_linux_mips64le_softfloat.zip](https://github.com/Mmx233/BitSrunLoginGo/files/11645720/bitsrun_linux_mips64le_softfloat.zip)
[bitsrun_linux_mipsle.zip](https://github.com/Mmx233/BitSrunLoginGo/files/11645721/bitsrun_linux_mipsle.zip)
[bitsrun_linux_mipsle_softfloat.zip](https://github.com/Mmx233/BitSrunLoginGo/files/11645722/bitsrun_linux_mipsle_softfloat.zip)
[bitsrun_linux_ppc64.zip](https://github.com/Mmx233/BitSrunLoginGo/files/11645723/bitsrun_linux_ppc64.zip)
[bitsrun_linux_ppc64le.zip](https://github.com/Mmx233/BitSrunLoginGo/files/11645724/bitsrun_linux_ppc64le.zip)
[bitsrun_linux_riscv64.zip](https://github.com/Mmx233/BitSrunLoginGo/files/11645725/bitsrun_linux_riscv64.zip)
[bitsrun_linux_s390x.zip](https://github.com/Mmx233/BitSrunLoginGo/files/11645726/bitsrun_linux_s390x.zip)
[bitsrun_netbsd_386.zip](https://github.com/Mmx233/BitSrunLoginGo/files/11645727/bitsrun_netbsd_386.zip)
[bitsrun_netbsd_amd64.zip](https://github.com/Mmx233/BitSrunLoginGo/files/11645728/bitsrun_netbsd_amd64.zip)
[bitsrun_netbsd_arm.zip](https://github.com/Mmx233/BitSrunLoginGo/files/11645729/bitsrun_netbsd_arm.zip)
[bitsrun_netbsd_arm64.zip](https://github.com/Mmx233/BitSrunLoginGo/files/11645730/bitsrun_netbsd_arm64.zip)
[bitsrun_openbsd_386.zip](https://github.com/Mmx233/BitSrunLoginGo/files/11645731/bitsrun_openbsd_386.zip)
[bitsrun_openbsd_amd64.zip](https://github.com/Mmx233/BitSrunLoginGo/files/11645732/bitsrun_openbsd_amd64.zip)
[bitsrun_openbsd_arm.zip](https://github.com/Mmx233/BitSrunLoginGo/files/11645733/bitsrun_openbsd_arm.zip)
[bitsrun_openbsd_arm64.zip](https://github.com/Mmx233/BitSrunLoginGo/files/11645734/bitsrun_openbsd_arm64.zip)
[bitsrun_solaris_amd64.zip](https://github.com/Mmx233/BitSrunLoginGo/files/11645735/bitsrun_solaris_amd64.zip)
[bitsrun_windows_386.zip](https://github.com/Mmx233/BitSrunLoginGo/files/11645736/bitsrun_windows_386.zip)
[bitsrun_windows_amd64.zip](https://github.com/Mmx233/BitSrunLoginGo/files/11645737/bitsrun_windows_amd64.zip)
[bitsrun_windows_arm.zip](https://github.com/Mmx233/BitSrunLoginGo/files/11645738/bitsrun_windows_arm.zip)
[bitsrun_windows_arm64.zip](https://github.com/Mmx233/BitSrunLoginGo/files/11645699/bitsrun_windows_arm64.zip)

**Comment by Mmx233** [comment]
自动查找 acid
