### ISSUE TITLE
作者有考虑加入ipv6支持吗

### ISSUE THREAD

**Issue by JasonFeng02** [Mmx233/BitSrunLoginGo#27]
当前cernet等主流校园网线路商在ipv6资源上比v4更丰富，但是通过脚本自动登录的话会没有ipv6 ip下发，只有v4单栈

**Comment by Mmx233** [comment]
目前没有哪个功能是和 ipv6 强关联的，ddns 主要用于方便校内网通信

**Comment by Mmx233** [comment]
我并不清除 ipv6 不下发是什么原因导致的，有线连接的情况下在宿舍手动登录一样没有 ipv6

**Comment by JasonFeng02** [comment]
了解了，我当前所在的地方会下发ipv6地址，但是fe80前缀，经过脚本的链接会默认ipv4单栈，ipv6一栏会直接返回false
![image](https://github.com/Mmx233/BitSrunLoginGo/assets/92613744/aeb64d90-bfc3-4da8-8930-92104a978e18)

**Comment by Mmx233** [comment]
你能对比一下 debug 模式下输出的表单和真实登录区别在哪吗，有这个我就能完成程序修改
