### ISSUE TITLE
状态异常，无匹配

### ISSUE THREAD

**Issue by xcf13363175** [Mmx233/BitSrunLoginGo#3]
尝试放到X86的openwrt软路由中，反馈状态异常，无匹配。账号、密码、user_type都设置成功。

**Comment by xcf13363175** [comment]
感觉和https://github.com/Mmx233/BitSrunLoginGo/issues/2是一个问题，但是不会魔改=。=

**Comment by Mmx233** [comment]
> 感觉和https://github.com/Mmx233/BitSrunLoginGo/issues/2 是一个问题，但是不会魔改=。=

用电脑正常登陆吗

**Comment by Mmx233** [comment]
> 用电脑也是显示同样的，然后窗口就没了

试试v2.6

**Comment by xcf13363175** [comment]
2021/12/02 10:23:04 Step0: 检查状态…
2021/12/02 10:23:05 Step1: 正在获取客户端ip
2021/12/02 10:23:05 Step2: 正在获取Token
2021/12/02 10:23:05 Step3: 执行登录…
2021/12/02 10:23:05 登录结果: login_error
2021/12/02 10:23:05 jQuery112401157665({"client_ip":"10.15.0.X","ecode":"E2901","error":"login_error","error_msg":"E2901: (Third party 1)ldap_first_entry error","online_ip":"10.15.0.X","res":"login_error","srun_ver":"SRunCGIAuthIntfSvr V1.18 B20211026","st":1638411786})
2021/12/02 10:23:05 运行出错，状态异常

找到了错误信息代码
E2901: "第三方认证接口返回的错误信息",

**Comment by Mmx233** [comment]
那我也没啥办法（捂脸
不在现场比较难适配

**Comment by xcf13363175** [comment]
已经搞定，meta参数没有设置好

**Comment by Mmx233** [comment]
V3.1切换了ip获取方式，能否测试一下能不能用，谢谢
