### ISSUE TITLE
脚本登录上了但上不了网

### ISSUE THREAD

**Issue by BUPT-zeld151** [Mmx233/BitSrunLoginGo#35]
其实是原版程序报的错，但原版程序已经停止维护很久了，所以借贵地一问。系统为ubuntu20.04，直插网线，运行脚本则持续不断重复登录过程step1-3，并输出ip_already_online_error。
ping外网能ping通，但是打开浏览器上不了网，浏览器打开登录页面显示已经登录成功，ip管理界面看得到本机ip在线。如果手动注销再手动从浏览器登录页面输入账户密码登录，则可以上网。
但问题是我在另一台链接实验室WiFi的笔记本win10系统上运行原版脚本，则可以正常自动连接网络。
所以我的问题出在哪里？应该如何改动？还是说我应该把直插网线改为连接WiFi？

**Comment by Mmx233** [comment]
要不试试登录前重启一下网卡

**Comment by BUPT-zeld151** [comment]
> 要不试试登录前重启一下网卡

经过试验并没有起作用。并且观察到在中关村校区北区可以用mac复现出此错误，截图如下
<img width="384" alt="image" src="https://github.com/Mmx233/BitSrunLoginGo/assets/49987126/d831cf86-8a5d-4da3-9430-17ae1785ead6">

**Comment by Mmx233** [comment]
那很可能与深澜无感知认证有关，可以尝试在深澜自主管理后台移除无感知认证
