### ISSUE TITLE
RUC登录无响应问题

### ISSUE THREAD

**Issue by enYao39** [Mmx233/BitSrunLoginGo#42]
在尝试使用本项目进行RUC网页认证时，出现无响应输出，已知config配置无误，日志如下
![image](https://github.com/user-attachments/assets/e846a0cd-da4b-47ff-a745-345b1a68d23a)
尝试使用[BIT-srun-login-script](https://github.com/coffeehat/BIT-srun-login-script)进行认证返回```Failed to resolve IP```
但是使用[RUC_WiFi](https://github.com/zyxuaan/RUC_WiFi)可以正常认证，对比两种python脚本，初步发现在获取用户ip上实现不同，以下是可以正常使用的脚本的实现
![image](https://github.com/user-attachments/assets/3be43ca5-59f0-48ca-a1ee-3011a44a33ea)
![image](https://github.com/user-attachments/assets/efcff8b3-2346-4b79-b7b6-bc54080dca60)
能否增加对RUC校园网的支持，希望在路由器上运行可执行文件

**Comment by Mmx233** [comment]
贵校深澜版本可能过新或过旧，希望可以贴出版本号。目前主体逻辑需要比较大的变更才能兼容此版本

**Comment by Hazard-cn** [comment]
> 贵校深澜版本可能过新或过旧，希望可以贴出版本号。目前主体逻辑需要比较大的变更才能兼容此版本

 不好意思，请问版本号应该如何查看呢

**Comment by enYao39** [comment]
按照[BIT-srun-login-script](https://zhuanlan.zhihu.com/p/122556315)知乎上查询网页response，并没有返回具体的客户端版本，目前了解到学校在2020年9月换用深澜认证，深澜官方给出的使用案例中说明了使用的是深澜4K版本，但是无法得知具体版本号。是否有其他方法查询版本号？

**Comment by Mmx233** [comment]
一般就是会直接在接口响应给出来的，参考 https://github.com/Mmx233/BitSrunLoginGo/issues/34

目前可以推测为较旧或魔改版本

**Comment by Mmx233** [comment]
我今天晚上改改看

**Comment by Mmx233** [comment]
已完成修改，请进行测试。由于增加了额外的跳过机制，测试时需要确保 `meta.double_stack` 为 `false`，并开启调试日志确认获取到了正确的 IP

test binaries:

[bitsrun_linux_386.tar.gz](https://github.com/user-attachments/files/17531298/bitsrun_linux_386.tar.gz)
[bitsrun_linux_amd64.tar.gz](https://github.com/user-attachments/files/17531299/bitsrun_linux_amd64.tar.gz)
[bitsrun_linux_arm.tar.gz](https://github.com/user-attachments/files/17531300/bitsrun_linux_arm.tar.gz)
[bitsrun_linux_arm64.tar.gz](https://github.com/user-attachments/files/17531301/bitsrun_linux_arm64.tar.gz)
[bitsrun_linux_mips.tar.gz](https://github.com/user-attachments/files/17531302/bitsrun_linux_mips.tar.gz)
[bitsrun_linux_mips_softfloat.tar.gz](https://github.com/user-attachments/files/17531303/bitsrun_linux_mips_softfloat.tar.gz)
[bitsrun_linux_mips64.tar.gz](https://github.com/user-attachments/files/17531305/bitsrun_linux_mips64.tar.gz)
[bitsrun_linux_mips64_softfloat.tar.gz](https://github.com/user-attachments/files/17531306/bitsrun_linux_mips64_softfloat.tar.gz)
[bitsrun_linux_mips64le.tar.gz](https://github.com/user-attachments/files/17531307/bitsrun_linux_mips64le.tar.gz)
[bitsrun_linux_mips64le_softfloat.tar.gz](https://github.com/user-attachments/files/17531308/bitsrun_linux_mips64le_softfloat.tar.gz)
[bitsrun_linux_mipsle.tar.gz](https://github.com/user-attachments/files/17531309/bitsrun_linux_mipsle.tar.gz)
[bitsrun_linux_mipsle_softfloat.tar.gz](https://github.com/user-attachments/files/17531310/bitsrun_linux_mipsle_softfloat.tar.gz)
[bitsrun_windows_386.tar.gz](https://github.com/user-attachments/files/17531311/bitsrun_windows_386.tar.gz)
[bitsrun_windows_amd64.tar.gz](https://github.com/user-attachments/files/17531312/bitsrun_windows_amd64.tar.gz)
[bitsrun_windows_arm.tar.gz](https://github.com/user-attachments/files/17531313/bitsrun_windows_arm.tar.gz)
[bitsrun_windows_arm64.tar.gz](https://github.com/user-attachments/files/17531314/bitsrun_windows_arm64.tar.gz)

**Comment by Mmx233** [comment]
Related to ab0eb1a5275efbca44d30592e00db27b60118f2a, 1ee261707a928d84ea18de6f7a526f93a9a6e313

**Comment by enYao39** [comment]
可以正确获取到IP了，测试日志如下，感谢大佬付出，那么我关闭issue了
![image](https://github.com/user-attachments/assets/8d03bfed-3b64-47a7-8de1-39a0ca57e225)
