### ISSUE TITLE
result cannot found from response

### ISSUE THREAD

**Issue by only-apple-can-do** [Mmx233/BitSrunLoginGo#44]
hello 这里是电子科大的

在未登录的情况下，`bitsrun` 登录报错 `result cannot found from response`，原因是请求用户信息的时候返回了

```json
{
    "client_ip": "113.54.155.x",
    "ecode": 0,
    "error": "not_online_error",
    "error_msg": "",
    "online_ip": "113.54.155.x",
    "res": "not_online_error",
    "srun_ver": "SRunCGIAuthIntfSvr V1.18 B20181212",
    "st": 1730530275
}
```

根据代码

https://github.com/Mmx233/BitSrunLoginGo/blob/e4193b477c6365f624ba783fcfb497e25620f18e/pkg/srun/srun.go#L49-L78

执行到 74 时 `online` 是 `nil`，`ip` 为 `113.54.155.x`，抛出错误 `ErrResultCannotFound` 是否是有意的？

另外，在上面的函数和后续处理中 `online` 从未被赋值为 `false`（的指针），代表 `if *online { ... } else { ... }` 中 `else` 的代码永远不会执行，也就是从来不会登录

https://github.com/Mmx233/BitSrunLoginGo/blob/e4193b477c6365f624ba783fcfb497e25620f18e/internal/login/login.go#L183-L229

---

我这里只针对我自己的环境做了测试，将

https://github.com/Mmx233/BitSrunLoginGo/blob/e4193b477c6365f624ba783fcfb497e25620f18e/pkg/srun/srun.go#L74

条件从或改为和。将 

https://github.com/Mmx233/BitSrunLoginGo/blob/e4193b477c6365f624ba783fcfb497e25620f18e/internal/login/login.go#L207

条件改为 `online != nil && *online` 可以正常登录

---

我不太清楚其他学校是否有这个问题，如果其他学校是正常的我后面有空的话花时间提个 pr 适配下我们学校的环境（

**Comment by Mmx233** [comment]
是 bug

**Comment by Mmx233** [comment]
请尝试 1.6.5
