### ISSUE TITLE
login_error 运行出错，状态异常

### ISSUE THREAD

**Issue by Alkaidcc** [Mmx233/BitSrunLoginGo#5]
版本：v3.1
日志如下：
![image](https://user-images.githubusercontent.com/54631354/158041000-78dc324c-0930-4e03-ada8-6e5a4bf17d27.png)
配置文件：
![image](https://user-images.githubusercontent.com/54631354/158041053-5147ee8b-e5b3-4335-a5df-ecd09c693bd5.png)
请问是哪里出错了？

**Comment by Mmx233** [comment]
请核对meta参数与运营商类型

**Comment by Alkaidcc** [comment]
> 请核对meta参数与运营商类型

meta参数根据浏览器 网络中的数据已经核对并修改了，并未找到`meta`中的`enc`字段值，并且经修改后重新运行仍然报同样的错误。
在登录状态下运行可以检测到已登录的状态。

**Comment by Mmx233** [comment]
这很奇怪，我们的深澜版本是一模一样的。建议观察贵校原登录网页是否在登录流程添加了额外的接口或者修改了参数名称

**Comment by Mmx233** [comment]
如果使用的是路由器，请尝试进行一次校时

**Comment by Mmx233** [comment]
![image](https://user-images.githubusercontent.com/36563672/158051750-ed0f1634-3480-4337-8bc8-898fca7b4fec.png)
这个错误我只在校园网崩溃的时候见过，摸不着头脑（

**Comment by Mmx233** [comment]
![image](https://user-images.githubusercontent.com/36563672/158051915-b344e933-45d6-4739-9a10-f0e93a6c7d2f.png)
env参数确实在请求无法找到，只能在jquery.srun.portal1.js中通过搜索定位，因为都是相同的值所以没写进readme

**Comment by Alkaidcc** [comment]
找到问题所在了，学校的登录参数和该项目的参数不一样。经过打开浏览器中的网络数据包发现：
![image](https://user-images.githubusercontent.com/54631354/158055787-7327db15-26a1-49bd-af9a-7e2283b2d9fc.png)
callback的参数和作者实现的貌似不一致？(多了奇怪的数字和下划线)。项目里的实现貌似是 `callback := "jQuery" + timestamp`

但是根据报错 `login error` 来看，问题应该出在登录部分：
![image](https://user-images.githubusercontent.com/54631354/158055976-fdd0533d-6b03-4c0d-88b9-152f6481fdee.png)
也许是checksum校验失败导致的。

不过已经找到替代的项目了：https://github.com/Debuffxb/srun-go

感谢❤️！

**Comment by Mmx233** [comment]
> 找到问题所在了，学校的登录参数和该项目的参数不一样。经过打开浏览器中的网络数据包发现： ![image](https://user-images.githubusercontent.com/54631354/158055787-7327db15-26a1-49bd-af9a-7e2283b2d9fc.png) callback的参数和作者实现的貌似不一致？(多了奇怪的数字和下划线)。项目里的实现貌似是 `callback := "jQuery" + timestamp`
> 
> 但是根据报错 `login error` 来看，问题应该出在登录部分： ![image](https://user-images.githubusercontent.com/54631354/158055976-fdd0533d-6b03-4c0d-88b9-152f6481fdee.png) 也许是checksum校验失败导致的。
> 
> 不过已经找到替代的项目了：https://github.com/Debuffxb/srun-go
> 
> 感谢❤️！

看了下，确实是chksum算法不一样

https://github.com/Debuffxb/srun-go/blob/2737f6903b3b936bcd66abb6417974f7725fc8c6/main.go#L49

https://github.com/Mmx233/BitSrunLoginGo/blob/398ec630c9b6345937487bd40bea46cab4d6997f/v1/login.go#L81
