### ISSUE TITLE
运营商值为空时能否去掉@符号

### ISSUE THREAD

**Issue by zhjue** [Mmx233/BitSrunLoginGo#6]

**Comment by Mmx233** [comment]
请使用：
[autoLogin_darwin_amd64.zip](https://github.com/Mmx233/BitSrunLoginGo/files/8377392/autoLogin_darwin_amd64.zip)
[autoLogin_linux_386.zip](https://github.com/Mmx233/BitSrunLoginGo/files/8377393/autoLogin_linux_386.zip)
[autoLogin_linux_amd64.zip](https://github.com/Mmx233/BitSrunLoginGo/files/8377394/autoLogin_linux_amd64.zip)
[autoLogin_linux_arm.zip](https://github.com/Mmx233/BitSrunLoginGo/files/8377395/autoLogin_linux_arm.zip)
[autoLogin_linux_arm64.zip](https://github.com/Mmx233/BitSrunLoginGo/files/8377396/autoLogin_linux_arm64.zip)
[autoLogin_linux_mipsle.zip](https://github.com/Mmx233/BitSrunLoginGo/files/8377397/autoLogin_linux_mipsle.zip)
[autoLogin_windows_386.zip](https://github.com/Mmx233/BitSrunLoginGo/files/8377398/autoLogin_windows_386.zip)
[autoLogin_windows_amd64.zip](https://github.com/Mmx233/BitSrunLoginGo/files/8377399/autoLogin_windows_amd64.zip)
