### ISSUE TITLE
登录遇到一些问题

### ISSUE THREAD

**Issue by hotwa** [Mmx233/BitSrunLoginGo#7]
2022/05/02 13:47:58 [INFO] Step.0: ..................
2022/05/02 13:47:58 [DEBUG] HTTP GET http://202.114.177.246/cgi-bin/rad_user_info
2022/05/02 13:47:58 [DEBUG] jQuery1651499278712989803({"client_ip":"10.8.47.238","ecode":0,"error":"not_online_error","error_msg":"","online_ip":"10.8.47.238","res":"not_online_error","srun_ver":"SRunCGIAuthIntfSvr V1.18 B20201030","st":1651499360})
2022/05/02 13:47:58 [INFO] Step.1: .....................ip
2022/05/02 13:47:58 [DEBUG] ip: 10.8.47.238
2022/05/02 13:47:58 [INFO] Step.2: ............token
2022/05/02 13:47:58 [DEBUG] HTTP GET http://202.114.177.246/cgi-bin/get_challenge
2022/05/02 13:47:58 [DEBUG] jQuery1651499278730144442({"challenge":"e442a8fe5f36eba4616b3edcb05ecefd4d5545592a224121221805bbfc1579a3","client_ip":"10.8.47.238","ecode":0,"error":"ok","error_msg":"","expire":"60","online_ip":"10.8.47.238","res":"ok","srun_ver":"SRunCGIAuthIntfSvr V1.18 B20201030","st":1651499360})
2022/05/02 13:47:58 [DEBUG] token: e442a8fe5f36eba4616b3edcb05ecefd4d5545592a224121221805bbfc1579a3
2022/05/02 13:47:58 [INFO] Step.3: ...............
2022/05/02 13:47:58 [DEBUG] HTTP GET http://202.114.177.246/cgi-bin/srun_portal
2022/05/02 13:48:01 [DEBUG] jQuery1651499278739853264({"client_ip":"10.8.47.238","ecode":"","error":"login_error","error_msg":"INFO failed, BAS respond timeout.","online_ip":"10.8.47.238","res":"login_error","srun_ver":"SRunCGIAuthIntfSvr V1.18 B20201030","st":1651499363})
2022/05/02 13:48:01 [INFO] ............: login_error
2022/05/02 13:48:01 [FATAL] ...........................: login_error

**Comment by hotwa** [comment]
root@JDBoxV3:~# /root/autoLogin --config=/root/Config.yaml
2022/05/02 13:48:12 [INFO]  Step.0: 正在检查状态
2022/05/02 13:48:12 [DEBUG]  HTTP GET  http://202.114.177.246/cgi-bin/rad_user_info
2022/05/02 13:48:12 [DEBUG]  jQuery1651499292470919633({"client_ip":"10.8.47.238","ecode":0,"error":"not_online_error","error_msg":"","online_ip":"10.8.47.238","res":"not_online_error","srun_ver":"SRunCGIAuthIntfSvr V1.18 B20201030","st":1651499373})
2022/05/02 13:48:12 [INFO]  Step.1: 正在获取客户端ip
2022/05/02 13:48:12 [DEBUG]  ip:  10.8.47.238
2022/05/02 13:48:12 [INFO]  Step.2: 正在获取token
2022/05/02 13:48:12 [DEBUG]  HTTP GET  http://202.114.177.246/cgi-bin/get_challenge
2022/05/02 13:48:12 [DEBUG]  jQuery1651499292482917789({"challenge":"e442a8fe5f36eba4616b3edcb05ecefd4d5545592a224121221805bbfc1579a3","client_ip":"10.8.47.238","ecode":0,"error":"ok","error_msg":"","expire":"47","online_ip":"10.8.47.238","res":"ok","srun_ver":"SRunCGIAuthIntfSvr V1.18 B20201030","st":1651499373})
2022/05/02 13:48:12 [DEBUG]  token:  e442a8fe5f36eba4616b3edcb05ecefd4d5545592a224121221805bbfc1579a3
2022/05/02 13:48:12 [INFO]  Step.3: 执行登录…
2022/05/02 13:48:12 [DEBUG]  HTTP GET  http://202.114.177.246/cgi-bin/srun_portal
2022/05/02 13:48:15 [DEBUG]  jQuery1651499292491572803({"client_ip":"10.8.47.238","ecode":"","error":"login_error","error_msg":"INFO failed, BAS respond timeout.","online_ip":"10.8.47.238","res":"login_error","srun_ver":"SRunCGIAuthIntfSvr V1.18 B20201030","st":1651499376})
2022/05/02 13:48:15 [INFO]  登录结果: login_error
2022/05/02 13:48:15 [FATAL]  运行出错，状态异常:  login_error
panic: [FATAL]  运行出错，状态异常:  login_error

**Comment by Mmx233** [comment]
请检查各项参数是否配置正确。该报错对应“网络连接超时，请稍后重试”，应该是配置有误

**Comment by Mmx233** [comment]
另外，路由器时间貌似不对，建议使用ntp进行校时

**Comment by hotwa** [comment]
config timeserver 'ntp'&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; list server 'time.windows.com'&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;list server 'time1.aliyun.com'&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;list server 'ntp.sjtu.edu.cn'&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; list server '3.cn.pool.ntp.org'&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; list server 'stdtime.gov.hk'&nbsp; &nbsp; &nbsp; &nbsp;




---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月2日(周一) 晚上10:02
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Mmx233/BitSrunLoginGo] 登录遇到一些问题 (Issue #7)




 
另外，路由器时间貌似不对，建议使用ntp进行校时

**Comment by hotwa** [comment]
应该可以把相应超时时间默认值从5调整即可，其他参数以前都成功过



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月2日(周一) 晚上9:58
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Mmx233/BitSrunLoginGo] 登录遇到一些问题 (Issue #7)




 
请检查各项参数是否配置正确。该报错对应“网络连接超时，请稍后重试”，应该是配置有误

**Comment by Mmx233** [comment]
这个和程序设定超时时间没有关系喔，是校园网后端超时了

**Comment by hotwa** [comment]
不能多等待一下吗，手动用网页登录都没有问题



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月3日(周二) 上午8:36
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Mmx233/BitSrunLoginGo] 登录遇到一些问题 (Issue #7)




 
这个和程序设定超时时间没有关系喔，是校园网后端超时了

**Comment by Mmx233** [comment]
这和客户端等不等待没关系（

**Comment by hotwa** [comment]
![image](https://user-images.githubusercontent.com/49749136/166455820-843fa84a-bc4c-4e03-86c7-747702b498ab.png)

**Comment by hotwa** [comment]
使用windows客户端登录同样的问题
网页就能正常认证

**Comment by hotwa** [comment]
配置如下
`form:
  domain: 202.114.177.246
  username: "testaccount"
  usertype: cucc
  password: "password"
meta:
  "n": "200"
  type: "1"
  acid: "5"
  enc: srun_bx1
settings:
  basic:
    https: false
    skip_cert_verify: false
    timeout: 5
    interfaces: ""
  guardian:
    enable: false
    duration: 300
  daemon:
    enable: false
    path: .autoLogin
  debug:
    enable: true
    write_log: false
    log_path: ./`

**Comment by hotwa** [comment]
配置如下
```yaml
form:
  domain: 202.114.177.246
  username: "testaccount"
  usertype: cucc
  password: "password"
meta:
  "n": "200"
  type: "1"
  acid: "5"
  enc: srun_bx1
settings:
  basic:
    https: false
    skip_cert_verify: false
    timeout: 5
    interfaces: ""
  guardian:
    enable: false
    duration: 300
  daemon:
    enable: false
    path: .autoLogin
  debug:
    enable: true
    write_log: false
    log_path: ./
```

**Comment by Mmx233** [comment]
> 应该可以把相应超时时间默认值从5调整即可，其他参数以前都成功过
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年5月2日(周一) 晚上9:58 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [Mmx233/BitSrunLoginGo] 登录遇到一些问题 (Issue #7) 请检查各项参数是否配置正确。该报错对应“网络连接超时，请稍后重试”，应该是配置有误 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

你的意识是之前能成功，现在无法通过认证？

**Comment by hotwa** [comment]
是的，我之前认证都说放到路由的/etc/rc.local
重启路由就能认证，以往都成功了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月3日(周二) 晚上8:56
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Mmx233/BitSrunLoginGo] 登录遇到一些问题 (Issue #7)




  
应该可以把相应超时时间默认值从5调整即可，其他参数以前都成功过
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2022年5月2日(周一) 晚上9:58 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [Mmx233/BitSrunLoginGo] 登录遇到一些问题 (Issue #7) 请检查各项参数是否配置正确。该报错对应“网络连接超时，请稍后重试”，应该是配置有误 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
你的意识是之前能成功，现在无法通过认证？

**Comment by Mmx233** [comment]
那么是发生了什么导致无法认证的呢？什么都没动？升级了版本？

**Comment by Mmx233** [comment]
那么很可能是校方更改了参数，之后有重新核对过吗

**Comment by hotwa** [comment]
放假五一之后就没法自动认证了
我返回学校，就手动debug了看到这个错误，浏览器认证倒是正常

**Comment by hotwa** [comment]
账号密码没问题，网页都能登录

**Comment by hotwa** [comment]
要重新抓包？

**Comment by hotwa** [comment]
好吧，貌似现在，直接接路由器wan口，电脑接路由lan口，用网页认证之后，路由器就有网了，不过要手动，人不在学校了就不方便。还是x86软路由方便

**Comment by Mmx233** [comment]
如果问题仍然存在，欢迎提交新的 issue

**Comment by Grey0520** [comment]
我换了一下 acid 就登上了

**Comment by hotwa** [comment]
是的，后来我解决了这个问题了。我用了rust实现的那个版本，go的有点大
