### ISSUE TITLE
请问启动参数中的-daemon和-running-daemon有什么区别？

### ISSUE THREAD

**Issue by FurnaceCraft** [Mmx233/BitSrunLoginGo#9]

**Comment by FurnaceCraft** [comment]
此外设置daemon为true，在/etc/rc.local中设置自启动SrunLogin后并没有在进程列表中找到该进程，不清楚原因

**Comment by Mmx233** [comment]
-running-daemon是在开机启动的时候用的，若为守护模式，强制启用后台模式，以防开机流程堵塞在这

**Comment by Mmx233** [comment]
只有在守护模式下才会长时间驻留的，不然只认证一次

**Comment by FurnaceCraft** [comment]
原来如此，谢谢

**Comment by Mmx233** [comment]
啊，整反了不好意思，-daemon是开机启动的时候用的，-running-daemon是表示已经在daemon中，即为强制不daemon。
